bhand_joints_control:
  joint1:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_1/prox_joint
  joint2:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_1/med_joint
  joint3:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_1/dist_joint
  joint4:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_2/prox_joint
  joint5:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_2/med_joint
  joint6:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_2/dist_joint
  joint7:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_3/med_joint
  joint8:
    type: position_controllers/JointPositionController
    joint: wam/bhand/finger_3/dist_joint