base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  
  # Robot

#  acc_lim_x: 0.2
#  acc_lim_y: 0.2
#  acc_lim_th: 0.2
  acc_lim_x: 3.0
  acc_lim_y: 0.5
  acc_lim_th: 3.0
  acc_limit_trans: 3.0
  max_trans_vel: 3.0
#  min_trans_vel:
#  max_vel_x: 0.5
  max_vel_x: 3.0
  min_vel_x: -0.1
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_rot_vel: 3.0
  min_rot_vel: 0.4

  # Goal Tolerance

#  yaw_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.5
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  # Forward Simulation

  sim_time: 4.0
  sim_granularity: 0.025
  vx_samples: 10.0
  vy_samples: 5.0
  vth_samples: 20.0
#  controller_frequency:

  # Trajectory Scoring

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.02
#  forward_point_distance:
#  stop_time_buffer:
#  scaling_speed:
#  max_scaling_factor:
#  publish_cost_grid:

  # Oscillation Prevention

  oscillation_reset_dist: 0.05

  # Global Plan

#  prune_plan:

  
